name = "SuperLattice"
uuid = "cfaeb0a2-ec06-458d-9f5f-e8dd09141425"
authors = ["Yixing Fu"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
